### ISSUE TITLE
Java and Swift Base 128 and 192 codec

### ISSUE THREAD

**Issue by zyc** [adanilo/base128codec#1]
Sorry about open a issue just to get in touch with you.

I'm interested to try these bases (128 and 192) on Java and Swift. Have you done this before? If you didn't do yet, I could translate your algorithm to both languages.

Is it fully tested?

Thanks and sorry again.

**Comment by adanilo** [comment]
Hi @zyc , sorry for the slow response.

I haven't tried to build this in either Java or Swift, but yes the code here is well tested.

Go for it, I'd be very curious to hear any results.
